using FieldGroove.Domain.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.pdf.draw;
using iTextSharp.text.pdf.parser;

namespace FieldGroove.Application.GenerateLeadPDF
{
    public class GenerateLeadPDF
    {

        public static byte[] LeadPDF(LeadsModel model)
        {
            using var Lead = new MemoryStream();
            var document = new Document(PageSize.A4, 25, 25, 30, 30);
            PdfWriter.GetInstance(document, Lead);

            document.Open();

            var titleFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD,20,BaseColor.BLACK); 
            var subTitleFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLDOBLIQUE,17,BaseColor.DARK_GRAY);

            document.Add(new Paragraph("Field Groove ", titleFont) { Alignment = Element.ALIGN_CENTER});
            document.Add(new Paragraph("Lead Is Created" , subTitleFont) { Alignment = Element.ALIGN_BASELINE, SpacingBefore=10f, SpacingAfter=20f });
            document.Add(new Paragraph("Lead Details"));

            PdfPTable table = new PdfPTable(2)
            {
                WidthPercentage = 100,
                SpacingBefore = 20f,
                SpacingAfter = 20f,
            };
            table.SetWidths(new float[] { 1f, 3f });

            void AddRow(string label, string value)
            {
                var cellLabel = new PdfPCell(new Phrase(label))
                {
                    //Border = Rectangle.,
                    PaddingBottom = 5f,
                    BackgroundColor = new BaseColor(240, 240, 240)
                };
                var cellValue = new PdfPCell(new Phrase(value))
                {
                    //Border = Rectangle.NO_BORDER,
                    PaddingBottom = 5f,
                    //BackgroundColor = new BaseColor(240, 240, 240)
                };
                table.AddCell(cellLabel);
                table.AddCell(cellValue);
            }

            AddRow("ID:", model.Id.ToString()!);
            AddRow("ProjectName:", model.ProjectName!);
            AddRow("Status:", model.Status!);
            AddRow("Added", model.Added.ToString()!);
            AddRow("Type",model.Type.ToString());
            AddRow("Contact", model.Contact.ToString());
            AddRow("Action",model.Action!);
            AddRow("Assignee", model.Assignee!);
            AddRow("BidDate",model.BidDate.ToString()!);

            document.Add(table);

            document.Add(new LineSeparator(1f, 100f, BaseColor.BLACK, Element.ALIGN_CENTER, 2));

            document.Add(new Paragraph("Generated by FieldGroove System")
            {
                Alignment = Element.ALIGN_CENTER,
                SpacingBefore = 20f
            });

            document.Close();

            return Lead.ToArray();
        }
    }
}
